apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: krushikar/discovery-server:latest
        ports:
        - containerPort: 8084
