apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: krushikar/inventory-service:latest
        ports:
        - containerPort: 8082
